services:
  users-db:
    image: postgres:16.1
    container_name: userDb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=users
      - POSTGRES_PASSWORD=users
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  tracker-service:
    build: tracker-service
    container_name: tracker-service
    ports:
      - "8080:8080"
    depends_on:
      - users-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://users-db:5432/users
      - SPRING_DATASOURCE_USERNAME=users
      - SPRING_DATASOURCE_PASSWORD=users