server:
  port: 8081
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/users
    username: users
    password: users
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  sql:
    init:
      mode: always
  oauth2:
    client:
      preEstablishedRedirectUrl: http://62.109.21.174:8081/api/v1/apps/auth/login
token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
wialon:
  url: "https://hosting.wln-hst.com/login.html"
config:
  url: http://62.109.21.174:8081