drop table IF EXISTS users, roles, users_roles CASCADE;

create table IF NOT EXISTS token_wialon (
        data_created timestamp(6) not null,
        id bigint generated by default as identity,
        local_date_time timestamp(6) not null,
        name varchar(512) not null UNIQUE,
        primary key (id)
    );

create table IF NOT EXISTS token_access (
        id bigint generated by default as identity,
        data_created timestamp(6) not null,
        end_data timestamp(6) not null,
        name varchar(512) not null UNIQUE,
        primary key (id)
    );

create table IF NOT EXISTS users (
        created_at timestamp(6),
        id bigint generated by default as identity,
        token_wialon_id bigint REFERENCES token_wialon(id) ON DELETE CASCADE,
        token_access_id bigint REFERENCES token_access(id) ON DELETE CASCADE,
        updated_at timestamp(6),
        email varchar(255) not null unique,
        password varchar(255) not null,
        real_password varchar(255) not null,
        username varchar(255) not null unique,
        primary key (id)
    );

create TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(255),
    PRIMARY KEY (id)
);

create TABLE IF NOT EXISTS users_roles (
    user_id BIGINT REFERENCES users(id) ON delete CASCADE,
    roles_id BIGINT REFERENCES roles(id) ON delete CASCADE,
    PRIMARY KEY (user_id, roles_id)
);

create table IF NOT EXISTS item (
        created timestamp(6),
        id bigint generated by default as identity,
        message varchar(255),
        primary key (id)
    );



INSERT INTO roles ("name") VALUES ('ROLE_ADMIN');
INSERT INTO roles ("name") VALUES ('ROLE_USER');
INSERT INTO users ("username", "email", "password", "real_password") VALUES ('admin', 'admin@admin.ru', '$2a$10$X2teDL0gpmVgA4MKsk6HvO0po0u7fpYGfWFvHnkMMOLX6enZvkbPm', 'admin');
INSERT INTO users_roles VALUES (1,1);


