 create table IF NOT EXISTS eid (
        count integer not null,
        end_time timestamp(6),
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

create table IF NOT EXISTS token_wialon (
        data_created timestamp(6) not null,
        id bigint generated by default as identity,
        end_data timestamp(6) not null,
        name varchar(512) not null UNIQUE,
        primary key (id)
    );

create table IF NOT EXISTS token_access (
        id bigint generated by default as identity,
        data_created timestamp(6) not null,
        end_data timestamp(6) not null,
        name varchar(512) not null unique,
        primary key (id)
    );

create table IF NOT EXISTS users (
        created_at timestamp(6),
        eid_id bigint unique REFERENCES token_wialon(id),
        id bigint generated by default as identity,
        token_wialon_id bigint unique REFERENCES token_wialon(id),
        token_access_id bigint unique REFERENCES token_access(id),
        updated_at timestamp(6),
        email varchar(255) not null unique,
        password varchar(255) not null,
        real_password varchar(255) not null,
        username varchar(255) not null unique,
        primary key (id)
    );

create TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(255),
    PRIMARY KEY (id)
);

create TABLE IF NOT EXISTS users_roles (
    user_id BIGINT REFERENCES users(id) ON delete CASCADE,
    roles_id BIGINT REFERENCES roles(id) ON delete CASCADE,
    PRIMARY KEY (user_id, roles_id)
);

create table IF NOT EXISTS message (
        p integer not null,
        s integer not null,
        t integer not null,
        date timestamp(6) with time zone,
        id bigint generated by default as identity,
        address varchar(255),
        car varchar(255),
        primary key (id)
    );



INSERT INTO roles (name)VALUES ('ROLE_ADMIN') ON CONFLICT (name) DO NOTHING;
INSERT INTO roles (name)VALUES ('ROLE_USER') ON CONFLICT (name) DO NOTHING;


