drop table IF EXISTS users, roles, user_role;

    create TABLE IF NOT EXISTS users (
    created_at TIMESTAMP(6),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    updated_at TIMESTAMP(6),
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

    create TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY (id)
);
create TABLE IF NOT EXISTS users_roles (
    user_id BIGINT REFERENCES users(id),
    roles_id BIGINT REFERENCES roles(id),
    PRIMARY KEY (user_id, roles_id)
);

INSERT INTO roles ("name")
	VALUES ('ROLE_ADMIN');
INSERT INTO roles ("name")
	VALUES ('ROLE_USER');

